INSERT INTO artists (name, max_range) VALUES ( 'SEXMACHINEGUNS', 4);
INSERT INTO artists (name, max_range) VALUES ( 'MISIA', 6);
INSERT INTO artists (name, max_range) VALUES ( '浜田麻里', 4);
INSERT INTO artists (name, max_range) VALUES ( 'ステファニー', 4);
INSERT INTO artists (name, max_range) VALUES ( '大黒摩季', 6);
INSERT INTO artists (name, max_range) VALUES ( 'VOW VOW', 4);
INSERT INTO artists (name, max_range) VALUES ( 'Superfly', 6);
INSERT INTO artists (name, max_range) VALUES ( 'TK from 凛として時雨', 4);
INSERT INTO artists (name, max_range) VALUES ( 'でんぱ組.inc', 4);
INSERT INTO artists (name, max_range) VALUES ( '広瀬香美', 6);
INSERT INTO artists (name, max_range) VALUES ( '宇浦冴香', 6);
INSERT INTO artists (name, max_range) VALUES ( 'LOUDNESS', 6);
INSERT INTO artists (name, max_range) VALUES ( 'nano.RIPE', 6);
INSERT INTO artists (name, max_range) VALUES ( '家入レオ', 6);
INSERT INTO artists (name, max_range) VALUES ( 'Dir en grey', 6);
INSERT INTO artists (name, max_range) VALUES ( 'AKINO', 8);
INSERT INTO artists (name, max_range) VALUES ( '西野カナ', 8);
INSERT INTO artists (name, max_range) VALUES ( 'モーニング娘。', 8);
INSERT INTO artists (name, max_range) VALUES ( 'LISA', 8);
INSERT INTO artists (name, max_range) VALUES ( 'チャットモンチー', 8);
INSERT INTO artists (name, max_range) VALUES ( 'Perfume', 8);
INSERT INTO artists (name, max_range) VALUES ( '平野綾', 8);
INSERT INTO artists (name, max_range) VALUES ( '宇多田ヒカル', 8);
INSERT INTO artists (name, max_range) VALUES ( 'globe', 8);
INSERT INTO artists (name, max_range) VALUES ( '愛内里菜', 8);
INSERT INTO artists (name, max_range) VALUES ( 'Lyrico', 8);
INSERT INTO artists (name, max_range) VALUES ( '松たか子', 8);
INSERT INTO artists (name, max_range) VALUES ( 'DREAMS COME TRUE', 8);
INSERT INTO artists (name, max_range) VALUES ( 'SPEED', 8);
INSERT INTO artists (name, max_range) VALUES ( '浜崎あゆみ', 8);
INSERT INTO artists (name, max_range) VALUES ( '欅坂48', 8);
INSERT INTO artists (name, max_range) VALUES ( 'X JAPAN', 8);
INSERT INTO artists (name, max_range) VALUES ( 'JUJU', 8);
INSERT INTO artists (name, max_range) VALUES ( 'JAM Project', 10);
INSERT INTO artists (name, max_range) VALUES ( '水樹奈々', 8);
INSERT INTO artists (name, max_range) VALUES ( '小野正利', 8);
INSERT INTO artists (name, max_range) VALUES ( '椎名林檎', 8);
INSERT INTO artists (name, max_range) VALUES ( '伊藤由奈', 8);
INSERT INTO artists (name, max_range) VALUES ( 'Hysteric Blue', 8);
INSERT INTO artists (name, max_range) VALUES ( '夏川りみ', 8);
INSERT INTO artists (name, max_range) VALUES ( 'プリンセスプリンセス', 8);
INSERT INTO artists (name, max_range) VALUES ( '乃木坂46', 8);
INSERT INTO artists (name, max_range) VALUES ( '福山芳樹', 8);
INSERT INTO artists (name, max_range) VALUES ( 'YUI', 10);
INSERT INTO artists (name, max_range) VALUES ( 'May J', 10);
INSERT INTO artists (name, max_range) VALUES ( 'KARA', 10);
INSERT INTO artists (name, max_range) VALUES ( 'いきものがかり', 10);
INSERT INTO artists (name, max_range) VALUES ( 'クリープハイプ', 10);
INSERT INTO artists (name, max_range) VALUES ( '奥華子', 10);
INSERT INTO artists (name, max_range) VALUES ( 'Kalafina', 10);
INSERT INTO artists (name, max_range) VALUES ( '安室奈美恵', 10);
INSERT INTO artists (name, max_range) VALUES ( '大塚愛', 10);
INSERT INTO artists (name, max_range) VALUES ( '絢香', 10);
INSERT INTO artists (name, max_range) VALUES ( 'ももいろクローバーZ', 10);
INSERT INTO artists (name, max_range) VALUES ( 'ONE OK ROCK', 12);
INSERT INTO artists (name, max_range) VALUES ( '稲葉浩志', 12);
INSERT INTO artists (name, max_range) VALUES ( 'GReeeeN', 12);
INSERT INTO artists (name, max_range) VALUES ( '青山テルマ', 12);
INSERT INTO artists (name, max_range) VALUES ( '影山ヒロノブ', 12);
INSERT INTO artists (name, max_range) VALUES ( 'AKB48', 12);
INSERT INTO artists (name, max_range) VALUES ( '剛力彩芽', 12);
INSERT INTO artists (name, max_range) VALUES ( 'MY LITTLE LOVER', 12);
INSERT INTO artists (name, max_range) VALUES ( 'Every Little Thing', 12);
INSERT INTO artists (name, max_range) VALUES ( 'ZARD', 12);
INSERT INTO artists (name, max_range) VALUES ( 'aiko', 12);
INSERT INTO artists (name, max_range) VALUES ( 'KOTOKO', 12);
INSERT INTO artists (name, max_range) VALUES ( 'EGOIST', 12);
INSERT INTO artists (name, max_range) VALUES ( 'surface', 14);
INSERT INTO artists (name, max_range) VALUES ( 'UVERworld', 14);
INSERT INTO artists (name, max_range) VALUES ( 'AAA', 14);
INSERT INTO artists (name, max_range) VALUES ( 'Acid Black Cherry', 14);
INSERT INTO artists (name, max_range) VALUES ( 'B’z', 14);
INSERT INTO artists (name, max_range) VALUES ( '東方神起', 14);
INSERT INTO artists (name, max_range) VALUES ( '倖田來未', 14);
INSERT INTO artists (name, max_range) VALUES ( '遠藤正明', 14);
INSERT INTO artists (name, max_range) VALUES ( 'サンボマスター', 14);
INSERT INTO artists (name, max_range) VALUES ( 'きゃりーぱみゅぱみゅ', 14);
INSERT INTO artists (name, max_range) VALUES ( '松崎しげる', 14);
INSERT INTO artists (name, max_range) VALUES ( '山口百恵', 14);
INSERT INTO artists (name, max_range) VALUES ( '里田まい', 14);
INSERT INTO artists (name, max_range) VALUES ( '高橋洋子', 16);
INSERT INTO artists (name, max_range) VALUES ( '松田聖子', 16);
INSERT INTO artists (name, max_range) VALUES ( 'GLAY', 16);
INSERT INTO artists (name, max_range) VALUES ( 'DA PUMP', 16);
INSERT INTO artists (name, max_range) VALUES ( 'ゴスペラーズ', 16);
INSERT INTO artists (name, max_range) VALUES ( 'Sumika', 16);
INSERT INTO artists (name, max_range) VALUES ( 'ORANGE RANGE', 16);
INSERT INTO artists (name, max_range) VALUES ( 'w-inds.', 16);
INSERT INTO artists (name, max_range) VALUES ( 'cune', 16);
INSERT INTO artists (name, max_range) VALUES ( 'max_rangeTALK', 16);
INSERT INTO artists (name, max_range) VALUES ( 'あいみょん', 16);
INSERT INTO artists (name, max_range) VALUES ( 'abingdon boys school', 16);
INSERT INTO artists (name, max_range) VALUES ( '小泉今日子', 16);
INSERT INTO artists (name, max_range) VALUES ( 'ゴールデンボンバー', 18);
INSERT INTO artists (name, max_range) VALUES ( '宮野真守', 18);
INSERT INTO artists (name, max_range) VALUES ( 'UNISON SQUARE GARDEN', 18);
INSERT INTO artists (name, max_range) VALUES ( 'Hey! Say! JUMP', 18);
INSERT INTO artists (name, max_range) VALUES ( '木村カエラ', 18);
INSERT INTO artists (name, max_range) VALUES ( 'T.M.Revolution', 18);
INSERT INTO artists (name, max_range) VALUES ( 'SIAM SHADE', 18);
INSERT INTO artists (name, max_range) VALUES ( 'ロードメジャー', 18);
INSERT INTO artists (name, max_range) VALUES ( '小田和正', 18);
INSERT INTO artists (name, max_range) VALUES ( 'エレファントカシマシ', 18);
INSERT INTO artists (name, max_range) VALUES ( 'L’Arc～en～Ciel', 18);
INSERT INTO artists (name, max_range) VALUES ( 'スピッツ', 18);
INSERT INTO artists (name, max_range) VALUES ( 'Janne Da Arc', 18);
INSERT INTO artists (name, max_range) VALUES ( 'ゆず', 18);
INSERT INTO artists (name, max_range) VALUES ( 'Sexy Zone', 18);
INSERT INTO artists (name, max_range) VALUES ( 'CHEMISTRY', 18);
INSERT INTO artists (name, max_range) VALUES ( 'Acid Black Cherry', 18);
INSERT INTO artists (name, max_range) VALUES ( 'シド', 18);
INSERT INTO artists (name, max_range) VALUES ( '秦基博', 18);
INSERT INTO artists (name, max_range) VALUES ( 'SPYAIR', 18);
INSERT INTO artists (name, max_range) VALUES ( 'ナオトインティライミ', 18);
INSERT INTO artists (name, max_range) VALUES ( 'Mr.Children', 20);
INSERT INTO artists (name, max_range) VALUES ( '三代目 J Soul Brothers', 20);
INSERT INTO artists (name, max_range) VALUES ( '矢沢永吉', 20);
INSERT INTO artists (name, max_range) VALUES ( 'Sexy Zone', 20);
INSERT INTO artists (name, max_range) VALUES ( '清水翔太', 20);
INSERT INTO artists (name, max_range) VALUES ( '中島みゆき', 20);
INSERT INTO artists (name, max_range) VALUES ( '和田アキ子', 20);
INSERT INTO artists (name, max_range) VALUES ( 'レミオロメン', 20);
INSERT INTO artists (name, max_range) VALUES ( 'ゲスの極み乙女。', 20);
INSERT INTO artists (name, max_range) VALUES ( 'WANDS', 20);
INSERT INTO artists (name, max_range) VALUES ( 'CHAGE and ASKA', 20);
INSERT INTO artists (name, max_range) VALUES ( 'back number', 20);
INSERT INTO artists (name, max_range) VALUES ( '槇原敬之', 20);
INSERT INTO artists (name, max_range) VALUES ( 'flumpool', 20);
INSERT INTO artists (name, max_range) VALUES ( 'ファンキー加藤', 20);
INSERT INTO artists (name, max_range) VALUES ( 'スキマスイッチ', 22);
INSERT INTO artists (name, max_range) VALUES ( '9mm Parabellum Bullet', 22);
INSERT INTO artists (name, max_range) VALUES ( '関ジャニ∞', 22);
INSERT INTO artists (name, max_range) VALUES ( 'つるの剛士', 22);
INSERT INTO artists (name, max_range) VALUES ( 'スガシカオ', 22);
INSERT INTO artists (name, max_range) VALUES ( 'VAMPS', 22);
INSERT INTO artists (name, max_range) VALUES ( 'マキシマムザホルモン', 22);
INSERT INTO artists (name, max_range) VALUES ( 'KANA-BOON', 22);
INSERT INTO artists (name, max_range) VALUES ( 'サカナクション', 22);
INSERT INTO artists (name, max_range) VALUES ( '氣志團', 22);
INSERT INTO artists (name, max_range) VALUES ( 'クマムシ', 22);
INSERT INTO artists (name, max_range) VALUES ( '美空ひばり', 22);
INSERT INTO artists (name, max_range) VALUES ( '大事MANブラザーズ', 22);
INSERT INTO artists (name, max_range) VALUES ( 'KAT-TUN', 24);
INSERT INTO artists (name, max_range) VALUES ( '湘南乃風', 24);
INSERT INTO artists (name, max_range) VALUES ( 'EXILE', 24);
INSERT INTO artists (name, max_range) VALUES ( 'サザンオールスターズ', 24);
INSERT INTO artists (name, max_range) VALUES ( 'ポルノグラフィティ', 24);
INSERT INTO artists (name, max_range) VALUES ( 'コブクロ', 24);
INSERT INTO artists (name, max_range) VALUES ( '嵐', 24);
INSERT INTO artists (name, max_range) VALUES ( 'ASIAN KUNG-FU GENERATION', 24);
INSERT INTO artists (name, max_range) VALUES ( '桑田佳祐', 24);
INSERT INTO artists (name, max_range) VALUES ( 'THE BACK HORN', 24);
INSERT INTO artists (name, max_range) VALUES ( 'TOKIO', 24);
INSERT INTO artists (name, max_range) VALUES ( 'Aqua Timez', 24);
INSERT INTO artists (name, max_range) VALUES ( 'ウルフルズ', 24);
INSERT INTO artists (name, max_range) VALUES ( 'FUNKY MONmax_range BABYS', 24);
INSERT INTO artists (name, max_range) VALUES ( 'SEKAI NO OWARI', 24);
INSERT INTO artists (name, max_range) VALUES ( '米津玄師', 24);
INSERT INTO artists (name, max_range) VALUES ( 'HYDE', 24);
INSERT INTO artists (name, max_range) VALUES ( 'DEEN', 26);
INSERT INTO artists (name, max_range) VALUES ( 'タッキー＆翼', 26);
INSERT INTO artists (name, max_range) VALUES ( 'ムック', 26);
INSERT INTO artists (name, max_range) VALUES ( '稲垣潤一', 26);
INSERT INTO artists (name, max_range) VALUES ( '山崎まさよし', 26);
INSERT INTO artists (name, max_range) VALUES ( 'SMAP', 28);
INSERT INTO artists (name, max_range) VALUES ( '平井堅', 28);
INSERT INTO artists (name, max_range) VALUES ( 'RADWINPS', 28);
INSERT INTO artists (name, max_range) VALUES ( 'ケツメイシ', 28);
INSERT INTO artists (name, max_range) VALUES ( '氷室京介', 28);
INSERT INTO artists (name, max_range) VALUES ( 'シャ乱Q', 28);
INSERT INTO artists (name, max_range) VALUES ( 'MONGOL800', 28);
INSERT INTO artists (name, max_range) VALUES ( 'チェッカーズ', 28);
INSERT INTO artists (name, max_range) VALUES ( 'BUMP OF CHICKEN', 28);
INSERT INTO artists (name, max_range) VALUES ( 'GACKT', 28);
INSERT INTO artists (name, max_range) VALUES ( 'HOME MADE 家族', 28);
INSERT INTO artists (name, max_range) VALUES ( '長渕剛', 30);
INSERT INTO artists (name, max_range) VALUES ( '尾崎豊', 30);
INSERT INTO artists (name, max_range) VALUES ( 'V6', 30);
INSERT INTO artists (name, max_range) VALUES ( 'ザ・クロマニヨンズ', 30);
INSERT INTO artists (name, max_range) VALUES ( '郷ひろみ', 30);
INSERT INTO artists (name, max_range) VALUES ( 'FLOW', 30);
INSERT INTO artists (name, max_range) VALUES ( 'H2O', 30);
INSERT INTO artists (name, max_range) VALUES ( '遊助', 30);
INSERT INTO artists (name, max_range) VALUES ( 'ヒルクライム', 30);
INSERT INTO artists (name, max_range) VALUES ( 'KinKi Kids', 30);
INSERT INTO artists (name, max_range) VALUES ( 'THE YELLOW MONmax_range', 30);
INSERT INTO artists (name, max_range) VALUES ( '井上陽水', 30);
INSERT INTO artists (name, max_range) VALUES ( 'ザ・ブルーハーツ', 30);
INSERT INTO artists (name, max_range) VALUES ( '羞恥心', 30);
INSERT INTO artists (name, max_range) VALUES ( 'MONmax_range　MAJIK', 30);
INSERT INTO artists (name, max_range) VALUES ( '森山直太朗', 32);
INSERT INTO artists (name, max_range) VALUES ( 'Dragon　Ash', 32);
INSERT INTO artists (name, max_range) VALUES ( '鈴木雅之', 32);
INSERT INTO artists (name, max_range) VALUES ( '氷川きよし', 32);
INSERT INTO artists (name, max_range) VALUES ('DOES', 32);
INSERT INTO artists (name, max_range) VALUES ('福山雅治', 34);
INSERT INTO artists (name, max_range) VALUES ('藤井フミヤ', 34);
INSERT INTO artists (name, max_range) VALUES ('反町隆史', 34);
INSERT INTO artists (name, max_range) VALUES ('寺尾聰', 34);
INSERT INTO artists (name, max_range) VALUES ('RIP SLYME', 34);